# Generated by Django 4.1.2 on 2022-11-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='custome_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.IntegerField()),
                ('cname', models.CharField(max_length=20)),
                ('cmail', models.CharField(max_length=30)),
                ('csubject', models.CharField(max_length=30)),
                ('cmessage', models.CharField(max_length=100)),
            ],
        ),
    ]
