# Generated by Django 4.1.2 on 2022-11-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snadhanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='custome_details',
        ),
    ]
